name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tnielsen2/cloudchirp:${{ github.ref_name }}

      - name: Run Docker Image
        env:
          APP_ENVIRONMENT: ${{ github.ref }}
        run: |
          docker run -e APP_ENVIRONMENT=${{ github.ref_name }} tnielsen2/cloudchirp:${{ github.ref_name }} /app/__main__.py
