name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tnielsen2/cloudchirp:${{ github.ref }}
          builder: docker
          file: Dockerfile

      - name: Run Docker Image
        env:
          APP_ENVIRONMENT: ${{ github.ref }}
        run: |
          docker run -e APP_ENVIRONMENT=$APP_ENVIRONMENT tnielsen2/cloudchirp /app/__main__.py
