name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tnielsen2/cloudchirp:${{ github.ref_name }}

      - name: Run Docker Image
        env:
          APP_DNS_DOMAIN: ${{ secrets.APP_DNS_DOMAIN }}
          APP_ENVIRONMENT: ${{ github.ref }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCOUNT_NAME: ${{ secrets.AWS_ACCOUNT_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          docker run \
          -e APP_DNS_DOMAIN=${{ env.APP_DNS_DOMAIN }} \
          -e APP_ENVIRONMENT=${{ env.APP_ENVIRONMENT }} \
          -e AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
          -e AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
          -e AWS_ACCOUNT_NAME=${{ env.AWS_ACCOUNT_NAME }} \
          -e AWS_DEFAULT_REGION=us-east-1 \
          tnielsen2/cloudchirp:${{ github.ref_name }}
